### ISSUE TITLE
Help I Can't Import sql

### ISSUE THREAD

**Issue by Zordon1337** [WhiteRedWolf/Eevee-osuserver#5]
![1](https://user-images.githubusercontent.com/65111609/152691799-1c1c5a09-797a-4116-b137-e1db5f23c474.png)
![2](https://user-images.githubusercontent.com/65111609/152691858-25fee33b-97b1-4acb-80b0-61067f500594.png)

**Comment by Eeveelution** [comment]
don't use this its a security hazard and this is just pure shit code
